// ==UserScript==
// @name Yas Check New Things min
// @namespace   *
// @include     *yastalker.com*
// @version     0.9
// ==/UserScript==
(function(k){function l(){for(var a=0;3>a;a++)f("http://yastalker.com"+c[a].c,function(b){b=b.getElementsByClassName(c[a].b)[0].getElementsByTagName("a")[0].href;localStorage.setItem(c[a].a,b.substr(b.indexOf("id=")+3))})}function m(){for(var a=0;3>a;a++)if(location.pathname==c[a].c){var b=document.getElementsByClassName(c[a].b)[0].getElementsByTagName("a")[0].href;localStorage.setItem(c[a].a,b.substr(b.indexOf("id=")+3));console.info("Clear count of "+c[a].a)}}function h(){n();k.setTimeout(h,3E4)}
    function n(){for(var a=[],b=0;3>b;b++)f("http://yastalker.com"+c[b].c,function(p){var e=b;a:for(var g=q,d=b;;){var f=p.getElementsByClassName(c[d].b)[g].getElementsByTagName("a")[0].href;if(f.substr(f.indexOf("id=")+3)==localStorage.getItem(c[d].a)||10<=g)break a;++g}a[e]=g||0});r(a)}function f(a,b){var c=new XMLHttpRequest;c.open("GET",a,!1);c.onreadystatechange=function(){if(4==c.readyState&&200==c.status){var a=document.createElement("div");a.innerHTML=c.responseText;b(a)}};c.send(null)}function t(){var a=
            document.createElement("div");a.id="pop-up-newThings";a.innerHTML="";document.body.appendChild(a)}function r(a){var b="",d=document.getElementById("pop-up-newThings");d.innerHTML="";for(var e=0;e<a.length;e++)0!=a[e]&&(b+='<p><img width="16" height="16" alt="" class="menu_icon2" src="http://yastalker.com'+c[e].f+'"><span style="color: #ffbe35;">'+a[e]+"</span></p>");d.innerHTML=b}if("yastalker.com"===location.hostname){var d=document.createElement("style");d.setAttribute("type","text/css");d.innerHTML=
            "#pop-up-newThings:empty{ background: url('./images/icons/mynetwork16.gif') no-repeat scroll center center #0a0b0f; } #pop-up-newThings { min-width: 60px; min-height: 35px; position: fixed; bottom: 10px; left: 10px; z-index: 100; border-left: 2px solid #977743;  background-color: #0a0b0f; color: #977743; text-align: left; padding: 10px 15px;  -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; } #pop-up-newThings p { margin: 0; padding: 5px 0; } #pop-up-newThings img{ vertical-align: top; } #pop-up-newThings span { font-size: 1.45em; font-weight: bold; font-family: Arial, Tahoma, Verdana; }";
        document.getElementsByTagName("head")[0].appendChild(d);var q=0,c={0:{b:"blogs_browse_item",c:"/browse_blogs.php",a:"blog_last_id",g:"\u041d\u043e\u0432\u044b\u0445 \u0431\u043b\u043e\u0433\u043e\u0432: ",f:"/images/icons/blog_blog16.gif"},1:{b:"polls_browse_item",c:"/browse_polls.php",a:"poll_last_id",g:"\u041d\u043e\u0432\u044b\u0445 \u043e\u043f\u0440\u043e\u0441\u043e\u0432: ",f:"/images/icons/poll_poll16.gif"},2:{b:"seClassList2",c:"/browse_classifieds.php",a:"classified_last_id",g:"\u041d\u043e\u0432\u044b\u0445 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0439: ",
            f:"/images/icons/classified_classified16.gif"}};localStorage.getItem("newThings")||(localStorage.setItem("newThings",!0),l());m();t();h()}})(window);